spring.application.name=ecommerce
# db source
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=Thoang123

# auto add/delete table
spring.jpa.hibernate.ddl-auto=update

# show SQL script in the console
spring.jpa.show-sql=true

# Signer key
jwt.signerKey=3213123219841204571290479012845790112570321512232109471920701927
