spring.application.name=ecommerce
# db source
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/demo_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# auto add/delete table
spring.jpa.hibernate.ddl-auto=update

# show SQL script in the console
spring.jpa.show-sql=true

# Signer key
jwt.signerKey=${JWT_SIGNERKEY}


# Vnpay sandbox config
vnp_PayUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp_ReturnUrl=https://9c85e391f04252.lhr.life
vnp_TmnCode=VJ986OG9
vnp_HashSecret=${VNP_HASH_SECRET}
vnp_ApiUrl=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction


# Cache - Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.cache.type=none 

# TTL
spring.cache.redis.time-to-live=60000

# liquidbase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Actuator
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.observations.key-values.application=ecommerce